### ISSUE TITLE
When you have to select the category, they are not displayed nested.

### ISSUE THREAD

**Issue by Natim** [sebastienbarbier/seven23_webapp#1]
![categories](https://user-images.githubusercontent.com/229453/27121570-2d5472da-50e8-11e7-8e34-8c289f4ea3c1.png)

**Comment by Natim** [comment]
![do](https://user-images.githubusercontent.com/229453/27121640-65f69a32-50e8-11e7-8d86-2ca576bd8b9e.png)

**Comment by sebastienbarbier** [comment]
The idea was to have a generic form field (AutoCompleteSelectField.js, used by category and currency), but nested values were too complex to implement in such a short dedicated time.

I always use autocomplete so never really bothered about it.

Should not take long to do so should be implemented in next release. Thanks @Natim !

**Comment by sebastienbarbier** [comment]
<img width="807" alt="capture d ecran 2017-07-24 a 16 40 26" src="https://user-images.githubusercontent.com/3018618/28528827-1df042da-708f-11e7-8244-ae1f00fedb1d.png">
Nesting has been implemented 👍 
Far from being perfect, we'll refactor in next big release.

**Comment by Natim** [comment]
thx
